
/*
 * Copyright (C) 2016  Jevgenijs Protopopovs <protopopov1122@yandex.ru>
 */
/*This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.*/
#ifndef YILI_OPCODES_H_
#define YILI_OPCODES_H_
#include "yoyo/core.h"

	//Do not edit this file. It is autogenerated. Edit opcodes.xml instead.
	#define VM_Halt 0x0
	#define VM_LoadConstant 0x1
	#define VM_LoadInteger 0x2
	#define VM_Copy 0x3
	#define VM_Push 0x4
	#define VM_Pop 0x5
	#define VM_Add 0x7
	#define VM_Subtract 0x8
	#define VM_Multiply 0x9
	#define VM_Divide 0xA
	#define VM_Modulo 0xB
	#define VM_Power 0xC
	#define VM_Negate 0xD
	#define VM_Not 0xE
	#define VM_LogicalNot 0xF
	#define VM_ShiftRight 0x10
	#define VM_ShiftLeft 0x11
	#define VM_Or 0x12
	#define VM_And 0x13
	#define VM_Xor 0x14
	#define VM_Compare 0x15
	#define VM_Test 0x16
	#define VM_Call 0x17
	#define VM_Return 0x18
	#define VM_NewObject 0x19
	#define VM_NewLambda 0x1A
	#define VM_NewOverload 0x1B
	#define VM_NewArray 0x1C
	#define VM_NewComplexObject 0x1D
	#define VM_GetField 0x1E
	#define VM_SetField 0x1F
	#define VM_NewField 0x20
	#define VM_DeleteField 0x21
	#define VM_ArrayGet 0x22
	#define VM_ArraySet 0x23
	#define VM_ArrayDelete 0x24
	#define VM_Throw 0x25
	#define VM_Catch 0x26
	#define VM_OpenCatch 0x27
	#define VM_CloseCatch 0x28
	#define VM_Jump 0x29
	#define VM_JumpIfFalse 0x2A
	#define VM_JumpIfTrue 0x2B
	#define VM_Nop 0x2C
	#define VM_Swap 0x2D
	#define VM_DirectJump 0x2E
	#define VM_DirectJumpIfTrue 0x2F
	#define VM_DirectJumpIfFalse 0x30
	#define VM_Subsequence 0x31
	#define VM_Iterator 0x32
	#define VM_Iterate 0x33
	#define VM_NewInterface 0x34
	#define VM_ChType 0x35
typedef struct Mnemonic{
	uint8_t opcode;
	wchar_t* mnemonic;
} Mnemonic;
extern struct Mnemonic Mnemonics[];
extern const size_t OPCODE_COUNT;
typedef YValue* (*OpcodeHandler)(int32_t, int32_t, int32_t, YThread*);
extern OpcodeHandler* Handlers;
void init_handlers(); 
#endif
