
/*
 * Copyright (C) 2016  Jevgenijs Protopopovs <protopopov1122@yandex.ru>
 */
/*This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License version 3 as published by
    the Free Software Foundation.
   .

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.*/
#ifndef YILI_OPCODES_H_
#define YILI_OPCODES_H_
#include "core.h"

	//Do not edit this file. It is autogenerated. Edit opcodes.xml instead.
	#define VM_Halt 0x0	/* Unused */
	#define VM_LoadConstant 0x1	/* Load constant(arg1) in register(arg0) */
	#define VM_LoadInteger 0x2	/* Load integer(arg1) in register(arg0) */
	#define VM_Copy 0x3	/* Copy register(arg1) to register(arg0) */
	#define VM_Push 0x4	/* Push register(arg0) to stack */
	#define VM_Pop 0x5	/* Pop from stack to register(arg0) */
	#define VM_Add 0x7	/* Add register(arg1) value to register(arg2) and save to register(arg0) */
	#define VM_Subtract 0x8	/* Add register(arg2) value from register(arg1) and save to register(arg0) */
	#define VM_Multiply 0x9	/* Multiply register(arg1) value by register(arg2) and save to register(arg0) */
	#define VM_Divide 0xA	/* Divide register(arg1) value by register(arg2) and save to register(arg0) */
	#define VM_Modulo 0xB	/* Divide register(arg1) value by register(arg2) and save remainder to register(arg0) */
	#define VM_Power 0xC	/* Raise register(arg1) value to the power register(arg2) and save to register(arg0) */
	#define VM_Negate 0xD	/* Get negative value of register(arg1) and save to register(arg0) */
	#define VM_Not 0xE	/* Perform binary not operation on register(arg1) and save to register(arg0) */
	#define VM_LogicalNot 0xF	/* Perform logical not to boolean register(arg1) and save to register(arg0) */
	#define VM_ShiftRight 0x10	/* Shift integer in register(arg1) by register(arg2) to right and save to register(arg0) */
	#define VM_ShiftLeft 0x11	/* Shift integer in register(arg1) by register(arg2) to left and save to register(arg0) */
	#define VM_Or 0x12	/* Perform binary or operation on register(arg1) and register(arg2) save result to register(arg0) */
	#define VM_And 0x13	/* Perform binary and operation on register(arg1) and register(arg2) save result to register(arg0) */
	#define VM_Xor 0x14	/* Perform binary xor operation on register(arg1) and register(arg2) save result to register(arg0) */
	#define VM_Compare 0x15	/* Compare values in register(arg1) and register(arg2) and save integer result in register(arg0) */
	#define VM_Test 0x16	/* Perform and command on register(arg1) and arg2 and save to register(arg0) */
	#define VM_Call 0x17	/* Pop argument count and arguments from stack(argc on top, args in reverse order), get scope from register(arg2)  if exists, execute lambda in register(arg1) with that arguments and scope and save result to register(arg0) */
	#define VM_Return 0x18	/* Return value from register(arg0) and exit procedure */
	#define VM_NewObject 0x19	/* Create new object with parent in register(arg1) and save result to register(arg0) */
	#define VM_NewLambda 0x1A	/* Pop method, vararg flag, argument count, argument identifiers and types, return type from stack, create lamnda with scope(arg2) from procedure(arg1) and save to register(arg0) */
	#define VM_NewOverload 0x1B
	#define VM_NewArray 0x1C
	#define VM_NewComplexObject 0x1D
	#define VM_GetField 0x1E
	#define VM_SetField 0x1F
	#define VM_NewField 0x20
	#define VM_DeleteField 0x21
	#define VM_ArrayGet 0x22
	#define VM_ArraySet 0x23
	#define VM_ArrayDelete 0x24
	#define VM_Throw 0x25
	#define VM_Catch 0x26
	#define VM_OpenCatch 0x27
	#define VM_CloseCatch 0x28
	#define VM_Goto 0x29
	#define VM_GotoIfFalse 0x2A
	#define VM_GotoIfTrue 0x2B
	#define VM_Nop 0x2C
	#define VM_Swap 0x2D
	#define VM_Jump 0x2E
	#define VM_JumpIfTrue 0x2F
	#define VM_JumpIfFalse 0x30
	#define VM_Subsequence 0x31
	#define VM_Iterator 0x32
	#define VM_Iterate 0x33
	#define VM_NewInterface 0x34
	#define VM_ChangeType 0x35
	#define VM_FastCompare 0x36
	#define VM_Increment 0x37
	#define VM_Decrement 0x38
	#define VM_PushInteger 0x39
	#define VM_GotoIfEquals 0x3A
	#define VM_JumpIfEquals 0x3B
	#define VM_GotoIfNotEquals 0x3C
	#define VM_JumpIfNotEquals 0x3D
	#define VM_GotoIfGreater 0x3E
	#define VM_JumpIfGreater 0x3F
	#define VM_GotoIfLesser 0x40
	#define VM_JumpIfLesser 0x41
	#define VM_GotoIfNotGreater 0x42
	#define VM_JumpIfNotGreater 0x43
	#define VM_GotoIfNotLesser 0x44
	#define VM_JumpIfNotLesser 0x45
	#define VM_CheckType 0x46
typedef struct Mnemonic{
	uint8_t opcode;
	wchar_t* mnemonic;
} Mnemonic;
extern struct Mnemonic Mnemonics[];
extern const size_t OPCODE_COUNT;
#endif
