
/*
 * Copyright (C) 2016  Jevgenijs Protopopovs <protopopov1122@yandex.ru>
 */
/*This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.*/
#include "yoyo/opcodes.h"
#include "yoyo/core.h"
//	Do not edit this file. It is autogenerated. Edit opcodes.xml instead.
Mnemonic Mnemonics[] = {
	{0x0, L"Halt"},
	{0x1, L"LoadConstant"},
	{0x2, L"LoadInteger"},
	{0x3, L"Copy"},
	{0x4, L"Push"},
	{0x5, L"Pop"},
	{0x7, L"Add"},
	{0x8, L"Subtract"},
	{0x9, L"Multiply"},
	{0xA, L"Divide"},
	{0xB, L"Modulo"},
	{0xC, L"Power"},
	{0xD, L"Negate"},
	{0xE, L"Not"},
	{0xF, L"LogicalNot"},
	{0x10, L"ShiftRight"},
	{0x11, L"ShiftLeft"},
	{0x12, L"Or"},
	{0x13, L"And"},
	{0x14, L"Xor"},
	{0x15, L"Compare"},
	{0x16, L"Test"},
	{0x17, L"Call"},
	{0x18, L"Return"},
	{0x19, L"NewObject"},
	{0x1A, L"NewLambda"},
	{0x1B, L"NewOverload"},
	{0x1C, L"NewArray"},
	{0x1D, L"NewComplexObject"},
	{0x1E, L"GetField"},
	{0x1F, L"SetField"},
	{0x20, L"NewField"},
	{0x21, L"DeleteField"},
	{0x22, L"ArrayGet"},
	{0x23, L"ArraySet"},
	{0x24, L"ArrayDelete"},
	{0x25, L"Throw"},
	{0x26, L"Catch"},
	{0x27, L"OpenCatch"},
	{0x28, L"CloseCatch"},
	{0x29, L"Jump"},
	{0x2A, L"JumpIfFalse"},
	{0x2B, L"JumpIfTrue"},
	{0x2C, L"Nop"},
	{0x2D, L"Swap"},
	{0x2E, L"DirectJump"},
	{0x2F, L"DirectJumpIfTrue"},
	{0x30, L"DirectJumpIfFalse"},
	{0x31, L"Subsequence"},
	{0x32, L"Iterator"},
	{0x33, L"Iterate"},
	{0x34, L"NewInterface"},
	{0x35, L"ChType"},
};
const size_t OPCODE_COUNT = 53;
