/*
 * Copyright (C) 2016  Jevgenijs Protopopovs <protopopov1122@yandex.ru>
 */
/*This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.*/

#include "headers/parser.h"

#define NEW_BINARY(op, left, right) optimize_node(newBinaryNode(op, left, right)) 
#define NEW_UNARY(op, arg) optimize_node(newUnaryNode(op, arg))

wchar_t* getSymbol(ParseHandle* handle, wchar_t* wcs) {
	for (size_t i = 0; i < handle->symbols_size; i++)
		if (wcscmp(handle->symbols[i], wcs) == 0)
			return handle->symbols[i];
	size_t i = handle->symbols_size;
	handle->symbols = realloc(handle->symbols,
			sizeof(wchar_t*) * (++handle->symbols_size));
	handle->symbols[i] = calloc(wcslen(wcs) + 1, sizeof(wchar_t));
	wcscpy(handle->symbols[i], wcs);
	return handle->symbols[i];
}

void addConstant(ParseHandle* handle, yconstant_t c) {
	size_t i = handle->constants_size++;
	handle->constants = realloc(handle->constants,
			sizeof(yconstant_t) * handle->constants_size);
	handle->constants[i] = c;
}

ytoken shift(ParseHandle* handle) {
	handle->tokens[0] = handle->tokens[1];
	handle->tokens[1] = handle->tokens[2];
	handle->tokens[2] = handle->tokens[3];
	handle->tokens[3] = lex(handle);
	return handle->tokens[0];
}

NewValidate(Constant_validate) {
	return AssertToken(handle->tokens[0], TokenConstant)
			|| AssertKeyword(handle->tokens[0], NullKeyword);
}
NewReduce(Constant_reduce) {
	if (AssertKeyword(handle->tokens[0], NullKeyword)) {
		shift(handle);
		return newNullNode();
	}
	yconstant_t cnst = handle->tokens[0].value.cnst;
	ExtractCoords(file, line, charPos, handle);
	shift(handle);
	YNode* node = newConstantNode(cnst);
	SetCoords(node, file, line, charPos);
	return node;
}

NewValidate(Identifier_validate) {
	return AssertToken(handle->tokens[0], TokenIdentifier);
}
NewReduce(Identifier_reduce) {
	wchar_t* id = handle->tokens[0].value.id;
	ExtractCoords(file, line, charPos, handle);
	shift(handle);
	YNode* node = newIdentifierReferenceNode(id);
	SetCoords(node, file, line, charPos);
	return node;
}

NewValidate(Parser_Array_validate) {
	return AssertOperator(handle->tokens[0], OpeningBracketOperator);
}
NewReduce(Parser_Array_reduce) {
	ExtractCoords(file, line, charPos, handle);
	shift(handle);
	if (AssertOperator(handle->tokens[0], ClosingBracketOperator)) {
		/*Array is empty*/
		shift(handle);
		YNode* node = newFilledArray(NULL, 0);
		SetCoords(node, file, line, charPos);
		return node;
	} else {
		/*Get first array element*/
		YNode* base;
		ExpectReduce(&base, expr, L"Expected expression", ;, handle);
		if (AssertOperator(handle->tokens[0], SemicolonOperator)) {
			/*It's autogenerated runtime. First element
			 * is array element but next is element count*/
			shift(handle);
			/*Get element count*/
			YNode* count;
			ExpectReduce(&count, expr, L"Expected expression", base->free(base),
					handle);
			ExpectOperator(handle->tokens[0], ClosingBracketOperator,
					L"Expected ']'", {
						base->free(base)
						;
						count->free(count)
						;
					}, handle);
			shift(handle);
			/*Return autogenerated array node*/
			YNode* out = newGeneratedArray(base, count);
			SetCoords(out, file, line, charPos);
			return out;
		} else {
			/*It's array definition*/
			size_t length = 1;
			YNode** array = malloc(sizeof(YNode*) * length);
			/*Save first element*/
			array[0] = base;
			/*Code to free allocated resources if error occurred*/
#define freestmt {\
                for (size_t i=0;i<length;i++) array[i]->free(array[i]);\
                free(array);\
			}
			Expect(
					AssertOperator(handle->tokens[0], CommaOperator)||AssertOperator(handle->tokens[0], ClosingBracketOperator),
					L"Expected ']' or ','", freestmt, handle);
			if (AssertOperator(handle->tokens[0], CommaOperator))
				shift(handle);
			while (!AssertOperator(handle->tokens[0], ClosingBracketOperator)) {
				/*Get next elements*/
				YNode* nd;
				ExpectReduce(&nd, expr, L"Expected expression", freestmt,
						handle);
				length++;
				array = realloc(array, sizeof(YNode*) * length);
				array[length - 1] = nd;
				Expect(
						AssertOperator(handle->tokens[0], CommaOperator)||AssertOperator(handle->tokens[0], ClosingBracketOperator),
						L"Expected ']' or ','", freestmt, handle);
				if (AssertOperator(handle->tokens[0], CommaOperator))
					shift(handle);
			}
			shift(handle);
#undef freestmt
			/*Build AST node and return it*/
			YNode* out = newFilledArray(array, length);
			SetCoords(out, file, line, charPos);
			return out;
		}
	}
}

NewValidate(Object_validate) {
	return AssertKeyword(handle->tokens[0], ObjectKeyword);
}
NewReduce(Object_reduce) {
	ExtractCoords(file, line, charPos, handle);
	YObjectNode* obj = (YObjectNode*) newObjectNode(NULL, NULL, 0, NULL, 0);
	shift(handle);
	/*Code to free allocated if error occurred*/
#define freestmt {\
        for (size_t i=0;i<obj->fields_length;i++) {\
            obj->fields[i].value->free(obj->fields[i].value);\
        }\
        free(obj->fields);\
        if (obj->parent!=NULL) obj->parent->free(obj->parent);\
        free(obj);\
    }
	if (AssertOperator(handle->tokens[0], ColonOperator)) {
		/*Get object parent if available*/
		shift(handle);
		ExpectReduce(&obj->parent, expression, L"Exprected expression",
				freestmt, handle);
	}
	/*If object has body then parse it*/
	if (AssertOperator(handle->tokens[0], OpeningBraceOperator)) {
		shift(handle);
		while (!AssertOperator(handle->tokens[0], ClosingBraceOperator)) {
			if (handle->grammar.function.validate(handle)) {
				/*Parse object method*/
				YNode* nd;
				Reduce(&nd, function, freestmt, handle);
				YFunctionNode* func = (YFunctionNode*) nd;
				/*Check if object contains methods with
				 * the same name. If contains then add overload
				 * then with current*/
				for (size_t i = 0; i < obj->methods_length; i++) {
					if (obj->methods[i].id == func->name) {
						obj->methods[i].count++;
						obj->methods[i].lambda = realloc(obj->methods[i].lambda,
								sizeof(YLambdaNode*) * obj->methods[i].count);
						obj->methods[i].lambda[obj->methods[i].count - 1] =
								func->lambda;
						free(func);
						func = NULL;
						break;
					}
				}
				/*If there is no methods with the same name
				 * then add this*/
				if (func != NULL) {
					obj->methods_length++;
					obj->methods = realloc(obj->methods,
							sizeof(YFunctionBlock) * obj->methods_length);
					obj->methods[obj->methods_length - 1].id = func->name;
					obj->methods[obj->methods_length - 1].count = 1;
					obj->methods[obj->methods_length - 1].lambda = malloc(
							sizeof(YLambdaNode*));
					obj->methods[obj->methods_length - 1].lambda[0] =
							func->lambda;
					free(func);
					func = NULL;
				}
			} else {
				/*It must be field definition.
				 * Get field name.*/
				if (!handle->tokens[0].type==TokenIdentifier) {
					ParseError(L"Expected identifier or '}'", freestmt, handle);
				}
				wchar_t* id = handle->tokens[0].value.id;
				shift(handle);
				YNode* type = NULL;
				/*If field has defined type then parse it*/
				if (AssertOperator(handle->tokens[0], MinusOperator)&&
				AssertOperator(handle->tokens[1], GreaterOperator)) {
					shift(handle);
					shift(handle);
					ExpectReduce(&type, expression, L"Expected expression",
							freestmt, handle);
				}
				ExpectOperator(handle->tokens[0], ColonOperator,
						L"Expected ':'", freestmt, handle);
				shift(handle);
				/*Get field value and add field to object*/
				YNode* value;
				ExpectReduce(&value, expression, L"Expected expression",
						freestmt, handle);
				obj->fields_length++;
				obj->fields = realloc(obj->fields,
						obj->fields_length * sizeof(ObjectNodeField));
				obj->fields[obj->fields_length - 1].id = id;
				obj->fields[obj->fields_length - 1].value = value;
				obj->fields[obj->fields_length - 1].type = type;
			}
		}
		shift(handle);
	}
#undef freestmt
	/*Build object node*/
	YNode* out = (YNode*) obj;
	SetCoords(out, file, line, charPos);
	return out;
}

NewValidate(Lambda_validate) {
	return AssertOperator(handle->tokens[0], DollarSignOperator);
}
NewReduce(Lambda_reduce) {
	ExtractCoords(file, line, charPos, handle);
	shift(handle);
	size_t length = 0;
	wchar_t** args = NULL;
	YNode** argTypes = NULL;
	bool vararg = false;
	ExpectOperator(handle->tokens[0], OpeningParentheseOperator, L"Expected '(",
			;, handle);
	shift(handle);
	/*Parsing lambda arguments*/
	while (!AssertOperator(handle->tokens[0], ClosingParentheseOperator)) {
		if (AssertOperator(handle->tokens[0], QueryOperator)) {
			/*It's vararg argument. It must be last*/
			vararg = true;
			shift(handle);
		}
		/*Get argument name*/
		ExpectToken(handle->tokens[0], TokenIdentifier, L"Expected identifier",
				{ free(args); for (size_t i=0;i<length;i++) if (argTypes[i]!=NULL) argTypes[i]->free(argTypes[i]); free(argTypes); },
				handle);
		length++;
		args = realloc(args, sizeof(wchar_t*) * length);
		argTypes = realloc(argTypes, sizeof(YNode*) * length);
		args[length - 1] = handle->tokens[0].value.id;
		argTypes[length - 1] = NULL;
		shift(handle);
		/*Check if argument has type*/
		if (AssertOperator(handle->tokens[0], MinusOperator)&&
		AssertOperator(handle->tokens[1], GreaterOperator)) {
			shift(handle);
			shift(handle);
			ExpectReduce(&argTypes[length - 1], expr, L"Expected expression",
					{ free(args); for (size_t i=0;i<length;i++) if (argTypes[i]!=NULL) argTypes[i]->free(argTypes[i]); free(argTypes); },
					handle);
		}

		/*Next token must be ',' or ')'*/
		Expect(
				AssertOperator(handle->tokens[0], CommaOperator) ||AssertOperator(handle->tokens[0], ClosingParentheseOperator),
				L"Expected ')' or ','",
				{ free(args); for (size_t i=0;i<length;i++) if (argTypes[i]!=NULL) argTypes[i]->free(argTypes[i]); free(argTypes); },
				handle);
		Expect(
				!(vararg&&!AssertOperator(handle->tokens[0], ClosingParentheseOperator)),
				L"Vararg must be last, argument",
				{ free(args); for (size_t i=0;i<length;i++) if (argTypes[i]!=NULL) argTypes[i]->free(argTypes[i]); free(argTypes); },
				handle);
		if (AssertOperator(handle->tokens[0], CommaOperator))
			shift(handle);
	}
	shift(handle);
	/*Check if lambda has return type*/
	YNode* retType = NULL;
	if (AssertOperator(handle->tokens[0], MinusOperator)&&
	AssertOperator(handle->tokens[1], GreaterOperator)) {
		shift(handle);
		shift(handle);
		ExpectReduce(&retType, expr, L"Expected expression",
				{ free(args); for (size_t i=0;i<length;i++) if (argTypes[i]!=NULL) argTypes[i]->free(argTypes[i]); free(argTypes); },
				handle);
	}
	/*Get lambda body*/
	YNode* body;
	ExpectReduce(&body, statement, L"Expected statement",
			{ free(args); for (size_t i=0;i<length;i++) if (argTypes[i]!=NULL) argTypes[i]->free(argTypes[i]); free(argTypes); if (retType!=NULL) retType->free(retType); },
			handle);
	/*Build lambda node*/
	YNode* out = newLambdaNode(false, args, argTypes, length, vararg, retType,
			body);
	SetCoords(out, file, line, charPos);
	return out;
}

NewValidate(Overload_validate) {
	return AssertKeyword(handle->tokens[0], OverloadKeyword);
}
NewReduce(Overload_reduce) {
	ExtractCoords(file, line, charPos, handle);
	shift(handle);
	shift(handle);
	size_t length = 0;
	YNode** lmbds = NULL;
	YNode* defLmbd = NULL;
	/*Code to free allocated resources if there will be an error*/
#define freestmt {\
                        for (size_t i=0;i<length;i++)\
                            lmbds[i]->free(lmbds[i]);\
                        free(lmbds);\
                        if (defLmbd!=NULL)\
                            defLmbd->free(defLmbd);\
                   }
	/*Get lambdas*/
	while (!AssertOperator(handle->tokens[0], ClosingParentheseOperator)) {
		if (defLmbd == NULL && AssertKeyword(handle->tokens[0], DefaultKeyword)) {
			/*It's default lambda*/
			shift(handle);
			/*Get argument name*/
			ExpectToken(handle->tokens[0], TokenIdentifier,
					L"Expects identifier", freestmt, handle);
			wchar_t* arg = handle->tokens[0].value.id;
			shift(handle);
			wchar_t** args = malloc(sizeof(wchar_t*));
			args[0] = arg;
			/*Get lambda body*/
			YNode* body;
			ExpectReduce(&body, statement, L"Expected statement",
					{freestmt; free(args);}, handle);
			YNode** argTypes = calloc(1, sizeof(YNode*));
			defLmbd = newLambdaNode(false, args, argTypes, 1, false, NULL,
					body);
		} else if (handle->grammar.expr.validate(handle)) {
			/*Get next lambda*/
			length++;
			lmbds = realloc(lmbds, sizeof(YNode*) * length);
			ExpectReduce(&lmbds[length - 1], expr, L"Expected expression",
					freestmt, handle);
		} else
			ParseError(L"Expected lambda or 'default'", freestmt, handle);
	}
	shift(handle);
#undef freestmt

	/*Build new overloaded lambda node*/
	YNode* out = newOverloadNode(lmbds, length, defLmbd);
	SetCoords(out, file, line, charPos);
	return out;
}

NewValidate(Interface_validate) {
	return AssertKeyword(handle->tokens[0], InterfaceKeyword);
}
NewReduce(Interface_reduce) {
	ExtractCoords(file, line, charPos, handle);
	shift(handle);
	YNode** parents = NULL;
	size_t parent_count = 0;
	if (AssertOperator(handle->tokens[0], ColonOperator)) {
		/*Get interface parent list*/
		shift(handle);
		YNode* p;
		/*Get first parent*/
		ExpectReduce(&p, expr, L"Expected expression", ;, handle);
		parents = realloc(parents, sizeof(YNode*) * (++parent_count));
		parents[0] = p;
		while (AssertOperator(handle->tokens[0], CommaOperator)) {
			/*Get next parents if available*/
			shift(handle);
			ExpectReduce(&p, expr, L"Expected expression", {
				for (size_t i = 0; i < parent_count; i++)
					parents[i]->free(parents[i])
					;
				free(parents)
				;
			}, handle);
			parents = realloc(parents, sizeof(YNode*) * (++parent_count));
			parents[parent_count - 1] = p;
		}
	}

	wchar_t** ids = NULL;
	YNode** types = NULL;
	size_t attr_count = 0;
	/*Get interface body if available*/
	if (AssertOperator(handle->tokens[0], OpeningBraceOperator)) {
		shift(handle);
		/*Code to free allocated resources if error occurred*/
#define freestmt {\
				for (size_t i=0;i<parent_count;i++)\
					parents[i]->free(parents[i]);\
				free(parents);\
				free(ids);\
				for (size_t i=0;i<attr_count;i++)\
					types[i]->free(types[i]);\
				free(types);\
		}
		while (!AssertOperator(handle->tokens[0], ClosingBraceOperator)) {
			/*Get field name*/
			ExpectToken(handle->tokens[0], TokenIdentifier,
					L"Expected identifier or '}'", freestmt, handle);
			wchar_t* id = handle->tokens[0].value.id;
			shift(handle);
			ExpectOperator(handle->tokens[0], ColonOperator, L"Expected ':'",
					freestmt, handle);
			shift(handle);
			/*Get field type*/
			YNode* n;
			ExpectReduce(&n, expression, L"Expected expression", freestmt,
					handle);
			attr_count++;
			/*Save name and type*/
			ids = realloc(ids, sizeof(wchar_t*) * attr_count);
			types = realloc(types, sizeof(YNode*) * attr_count);
			ids[attr_count - 1] = id;
			types[attr_count - 1] = n;
			if (!(AssertOperator(handle->tokens[0], ClosingBraceOperator)
					|| AssertToken(handle->tokens[0], TokenIdentifier))) {
				ParseError(L"Expected '}' or identifier", freestmt, handle);
			}
		}
		shift(handle);
#undef freestmt
	}
	/*Build interface node and return it*/
	YNode* inode = newInterfaceNode(parents, parent_count, ids, types,
			attr_count);
	SetCoords(inode, file, line, charPos);
	return inode;
}

NewValidate(Factor_validate) {
	return Validate(identifier, handle) || Validate(constant, handle)
			|| Validate(object, handle) || Validate(lambda, handle)
			|| Validate(overload, handle) || Validate(array, handle)
			|| Validate(interface, handle)
			|| AssertOperator(handle->tokens[0], OpeningParentheseOperator)
			|| AssertOperator(handle->tokens[0], OpeningBraceOperator);
}
NewReduce(Factor_reduce) {
	YNode* out = NULL;
	ExtractCoords(file, line, charPos, handle);
	if (Validate(identifier, handle))
		out = handle->grammar.identifier.reduce(handle);
	else if (Validate(constant, handle))
		out = handle->grammar.constant.reduce(handle);
	else if (AssertOperator(handle->tokens[0], OpeningParentheseOperator)) {
		shift(handle);
		ExpectReduce(&out, expression, L"Expected expression", ;, handle);
		ExpectOperator(handle->tokens[0], ClosingParentheseOperator,
				L"Expected ')'", ;, handle);
		shift(handle);
	} else if (Validate(object, handle))
		return handle->grammar.object.reduce(handle);
	else if (Validate(lambda, handle))
		return handle->grammar.lambda.reduce(handle);
	else if (Validate(overload, handle))
		return handle->grammar.overload.reduce(handle);
	else if (Validate(array, handle))
		return handle->grammar.array.reduce(handle);
	else if (Validate(interface, handle))
		return handle->grammar.interface.reduce(handle);
	else if (AssertOperator(handle->tokens[0], OpeningBraceOperator)) {
		/*It's block: '{' ... '}'
		 * Block may contain statements and function definitions*/
		YFunctionBlock* funcs = NULL;
		size_t funcs_c = 0;
		YNode** block = NULL;
		size_t length = 0;
		shift(handle);
		/*Code to free resources if error occurred*/
#define freestmt {\
	            for (size_t i=0;i<length;i++)\
	                block[i]->free(block[i]);\
	            free(block);\
	            for (size_t i=0;i<funcs_c;i++)\
	                for (size_t j=0;j<funcs[i].count;j++)\
	                    funcs[i].lambda[j]->node.free((YNode*) funcs[i].lambda[j]);\
	            free(funcs);\
			}
		while (!AssertOperator(handle->tokens[0], ClosingBraceOperator)) {
			if (handle->grammar.statement.validate(handle)) {
				/*Parse statement*/
				YNode* nd;
				ExpectReduce(&nd, statement, L"Expected statement", freestmt,
						handle);
				block = realloc(block, sizeof(YNode*) * (++length));
				block[length - 1] = nd;
			} else if (handle->grammar.function.validate(handle)) {
				/*Parse function definition*/
				YNode* nd;
				Reduce(&nd, function, freestmt, handle);
				YFunctionNode* func = (YFunctionNode*) nd;
				/*Check if block contains function with that name.
				 * If contains then overload them.*/
				for (size_t i = 0; i < funcs_c; i++)
					if (funcs[i].id == func->name) {
						funcs[i].count++;
						funcs[i].lambda = realloc(funcs[i].lambda,
								sizeof(YLambdaNode*) * funcs[i].count);
						funcs[i].lambda[funcs[i].count - 1] = func->lambda;
						free(func);
						func = NULL;
						break;
					}
				/*Else add function to block*/
				if (func != NULL) {
					funcs_c++;
					funcs = realloc(funcs, sizeof(YFunctionBlock) * funcs_c);
					funcs[funcs_c - 1].id = func->name;
					funcs[funcs_c - 1].count = 1;
					funcs[funcs_c - 1].lambda = malloc(sizeof(YLambdaNode*));
					funcs[funcs_c - 1].lambda[0] = func->lambda;
					free(func);
					func = NULL;
				}
			} else
				ParseError(L"Expected statement or function", freestmt, handle);
		}
#undef freestmt
		shift(handle);
		/*Build block node*/
		out = newBlockNode(block, length, funcs, funcs_c);
	} else
		ParseError(L"Expected expression", ;, handle);
	SetCoords(out, file, line, charPos);
	return out;
}

NewValidate(Reference_validate) {
	return Validate(factor, handle);
}
NewReduce(Reference_reduce) {
	YNode* node;
	ExtractCoords(file, line, charPos, handle);
	ExpectReduce(&node, factor, L"Expected expression", ;, handle);
	while (AssertOperator(handle->tokens[0], DotOperator)
			|| AssertOperator(handle->tokens[0], OpeningBracketOperator)
			|| AssertOperator(handle->tokens[0], OpeningParentheseOperator)) {
		if (AssertOperator(handle->tokens[0], DotOperator)) {
			shift(handle);
			ExpectToken(handle->tokens[0], TokenIdentifier,
					L"Expected identifier", node->free(node)
					;, handle);
			wchar_t* id = handle->tokens[0].value.id;
			shift(handle);
			YNode* field = newFieldReferenceNode(node, id);
			if (AssertOperator(handle->tokens[0], OpeningParentheseOperator)) {
				shift(handle);
				YNode** args = NULL;
				size_t len = 0;
#define freestmt {\
            					for (size_t i=0;i<len;i++) args[i]->free(args[i]);\
            					free(args);\
            					field->free(field);\
            				}
				while (!AssertOperator(handle->tokens[0],
						ClosingParentheseOperator)) {
					YNode* n;
					ExpectReduce(&n, expr, L"Expected expression", freestmt,
							handle);
					args = realloc(args, sizeof(YNode*) * (++len));
					args[len - 1] = n;
					if (AssertOperator(handle->tokens[0], CommaOperator))
						shift(handle);
					else if (!AssertOperator(handle->tokens[0],
							ClosingParentheseOperator))
						ParseError(L"Expected ')' or ','", freestmt, handle);
				}
				shift(handle);
				node = newCallNode(node, field, args, len);
#undef freestmt
			} else
				node = field;
		} else if (AssertOperator(handle->tokens[0], OpeningBracketOperator)) {
			shift(handle);
			YNode* left;
			ExpectReduce(&left, expression, L"Expected expression",
					node->free(node), handle);
			if (AssertOperator(handle->tokens[0], ColonOperator)) {
				shift(handle);
				YNode* right;
				ExpectReduce(&right, expression, L"Expected expression", {
					node->free(node)
					;
					left->free(left)
					;
				}, handle);
				ExpectOperator(handle->tokens[0], ClosingBracketOperator,
						L"Expected ']'", {
							node->free(node)
							;
							right->free(right)
							;
							left->free(left)
							;
						}, handle);
				shift(handle);
				node = newSubseqReferenceNode(node, left, right);
			} else {
				ExpectOperator(handle->tokens[0], ClosingBracketOperator,
						L"Expected ']'", {
							node->free(node)
							;
							left->free(left)
							;
						}, handle);
				shift(handle);
				node = newIndexReferenceNode(node, left);
			}
		} else if (AssertOperator(handle->tokens[0],
				OpeningParentheseOperator)) {
			shift(handle);
			YNode** args = NULL;
			size_t len = 0;
#define freestmt {\
					for (size_t i=0;i<len;i++) args[i]->free(args[i]);\
					free(args);\
					node->free(node);\
				}
			while (!AssertOperator(handle->tokens[0], ClosingParentheseOperator)) {
				YNode* n;
				ExpectReduce(&n, expr, L"Expected expression", freestmt, handle);
				args = realloc(args, sizeof(YNode*) * (++len));
				args[len - 1] = n;
				if (AssertOperator(handle->tokens[0], CommaOperator))
					shift(handle);
				else if (!AssertOperator(handle->tokens[0],
						ClosingParentheseOperator))
					ParseError(L"Expected ')' or ','", freestmt, handle);
			}
			shift(handle);
			node = newCallNode(NULL, node, args, len);
#undef freestmt
		}
	}
	SetCoords(node, file, line, charPos);
	return node;
}

NewValidate(Unary_validate) {
	return ((AssertOperator(handle->tokens[0], PlusOperator)
			&& AssertOperator(handle->tokens[1], PlusOperator))
			|| (AssertOperator(handle->tokens[0], MinusOperator)
					&& AssertOperator(handle->tokens[1], MinusOperator))
			|| AssertOperator(handle->tokens[0], PlusOperator)
			|| AssertOperator(handle->tokens[0], MinusOperator)
			|| AssertOperator(handle->tokens[0], NotOperator))
			|| handle->grammar.reference.validate(handle);
}
NewReduce(Unary_reduce) {
	YNode* unary = NULL;
	ExtractCoords(file, line, charPos, handle);
	if (AssertOperator(handle->tokens[0],
			PlusOperator) && AssertOperator(handle->tokens[1], PlusOperator)) {
		/*It has '++' in prefix*/
		shift(handle);
		shift(handle);
		/*Get argument and save PreIncrement operation*/
		YNode* arg;
		ExpectReduce(&arg, reference, L"Expected reference", ;, handle);
		unary = NEW_UNARY(PreIncrement, arg);
	}

	else if (AssertOperator(handle->tokens[0],
			MinusOperator) && AssertOperator(handle->tokens[1], MinusOperator)) {
		/*It has '--' in prefix*/
		shift(handle);
		shift(handle);
		/*Get argument and save PreDecrement operation*/
		YNode* arg;
		ExpectReduce(&arg, reference, L"Expected reference", ;, handle);
		unary = NEW_UNARY(PreDecrement, arg);
	}

	else if (AssertOperator(handle->tokens[0], PlusOperator)) {
		/* It's '+' operation
		 * Get argument and save it*/
		shift(handle);
		YNode* out;
		ExpectReduce(&out, reference, L"Expected reference", ;, handle);
		return out;
	}

	else if (AssertOperator(handle->tokens[0], MinusOperator)) {
		/* It's '-' operation
		 * Get argument and save Negate operation*/
		shift(handle);
		YNode* arg;
		ExpectReduce(&arg, reference, L"Expected reference", ;, handle);
		unary = NEW_UNARY(Negate, arg);
	}

	else if (AssertOperator(handle->tokens[0], NotOperator)) {
		/* It's '~' operation
		 * Get argument and save Not operation*/
		shift(handle);
		YNode* arg;
		ExpectReduce(&arg, reference, L"Expected reference", ;, handle);
		unary = NEW_UNARY(Not, arg);
	}

	else {
		/*It has no prefix. It may be just reference or
		 * PostIncrement or PostDecrement operation.*/
		YNode* out;
		ExpectReduce(&out, reference, L"Expected reference", ;, handle);

		if (AssertOperator(handle->tokens[0],
				PlusOperator) && AssertOperator(handle->tokens[1], PlusOperator)) {
			/* It's '++' operation
			 * Get argument and save PostIncrement operation*/
			shift(handle);
			shift(handle);
			unary = NEW_UNARY(PostIncrement, out);
		} else if (AssertOperator(handle->tokens[0],
				MinusOperator) && AssertOperator(handle->tokens[1], MinusOperator)) {
			/* It's '--' operation
			 * Get argument and save PostDecrement operation*/
			shift(handle);
			shift(handle);
			unary = NEW_UNARY(PostDecrement, out);
		}

		else {
			/*Return result*/
			SetCoords(out, file, line, charPos);
			return out;
		}

	}
	/*Return result*/
	SetCoords(unary, file, line, charPos);
	return unary;
}

NewValidate(Power_validate) {
	return Validate(unary, handle);
}
NewReduce(Power_reduce) {
	YNode* node;
	ExtractCoords(file, line, charPos, handle);
	ExpectReduce(&node, unary, L"Expected expression", ;, handle);
	while ((AssertOperator(handle->tokens[0], MultiplyOperator)
			&& AssertOperator(handle->tokens[1], MultiplyOperator))
			&& !AssertOperator(handle->tokens[2], AssignOperator)) {
		shift(handle);
		shift(handle);
		YNode* left;
		ExpectReduce(&left, unary, L"Expected expression", node->free(node)
		;, handle);
		node = NEW_BINARY(Power, node, left);
	}
	SetCoords(node, file, line, charPos);
	return node;
}

NewValidate(Mul_div_validate) {
	return Validate(power, handle);
}
NewReduce(Mul_div_reduce) {
	YNode* node;
	ExtractCoords(file, line, charPos, handle);
	ExpectReduce(&node, power, L"Expected expression", ;, handle);
	while ((AssertOperator(handle->tokens[0], MultiplyOperator)
			|| AssertOperator(handle->tokens[0], DivideOperator)
			|| AssertOperator(handle->tokens[0], ModuloOperator))
			&& !AssertOperator(handle->tokens[1], AssignOperator)) {
		YBinaryOperation op;
		if (AssertOperator(handle->tokens[0], MultiplyOperator))
			op = Multiply;
		if (AssertOperator(handle->tokens[0], DivideOperator))
			op = Divide;
		if (AssertOperator(handle->tokens[0], ModuloOperator))
			op = Modulo;
		shift(handle);
		YNode* left;
		ExpectReduce(&left, power, L"Expected expression", node->free(node)
		;, handle);
		node = NEW_BINARY(op, node, left);
	}
	SetCoords(node, file, line, charPos);
	return node;
}

NewValidate(Add_sub_validate) {
	return Validate(mul_div, handle);
}
NewReduce(Add_sub_reduce) {
	YNode* node;
	ExtractCoords(file, line, charPos, handle);
	ExpectReduce(&node, mul_div, L"Expected expression", ;, handle);
	while ((AssertOperator(handle->tokens[0], PlusOperator)
			|| AssertOperator(handle->tokens[0], MinusOperator))
			&& !AssertOperator(handle->tokens[1], AssignOperator)) {
		YBinaryOperation op;
		if (AssertOperator(handle->tokens[0], PlusOperator))
			op = Add;
		if (AssertOperator(handle->tokens[0], MinusOperator))
			op = Subtract;
		shift(handle);
		YNode* left;
		ExpectReduce(&left, mul_div, L"Expected expression", node->free(node)
		;, handle);
		node = NEW_BINARY(op, node, left);
	}
	SetCoords(node, file, line, charPos);
	return node;
}

NewValidate(Bitshift_validate) {
	return Validate(add_sub, handle);
}
NewReduce(Bitshift_reduce) {
	YNode* node;
	ExtractCoords(file, line, charPos, handle);
	ExpectReduce(&node, add_sub, L"Expected expression", ;, handle);
	while (((AssertOperator(handle->tokens[0], GreaterOperator)
			&& AssertOperator(handle->tokens[1], GreaterOperator))
			|| (AssertOperator(handle->tokens[0], LesserOperator)
					&& AssertOperator(handle->tokens[1], LesserOperator)))
			&& !AssertOperator(handle->tokens[2], AssignOperator)) {
		YBinaryOperation op;
		if (AssertOperator(handle->tokens[0], GreaterOperator))
			op = ShiftRight;
		else
			op = ShiftLeft;
		shift(handle);
		shift(handle);
		YNode* left;
		ExpectReduce(&left, add_sub, L"Expected expression", node->free(node)
			;, handle);
		node = NEW_BINARY(op, node, left);
	}
	SetCoords(node, file, line, charPos);
	return node;
}

NewValidate(Bitwise_validate) {
	return Validate(bitshift, handle);
}
NewReduce(Bitwise_reduce) {
	YNode* node;
	ExtractCoords(file, line, charPos, handle);
	ExpectReduce(&node, bitshift, L"Expected expression", ;, handle);
	while ((AssertOperator(handle->tokens[0], AndOperator)
			|| AssertOperator(handle->tokens[0], OrOperator)
			|| AssertOperator(handle->tokens[0], XorOperator))
			&& !AssertOperator(handle->tokens[1], AssignOperator)) {
		if (AssertOperator(handle->tokens[1], AndOperator)||
		AssertOperator(handle->tokens[1], OrOperator))
			break;
		YBinaryOperation op;
		if (AssertOperator(handle->tokens[0], AndOperator))
			op = And;
		if (AssertOperator(handle->tokens[0], OrOperator))
			op = Or;
		if (AssertOperator(handle->tokens[0], XorOperator))
			op = Xor;
		shift(handle);
		YNode* left;
		ExpectReduce(&left, bitshift, L"Expected expression", node->free(node)
		;, handle);
		node = NEW_BINARY(op, node, left);
	}
	SetCoords(node, file, line, charPos);
	return node;
}

NewValidate(Comparison_validate) {
	return Validate(bitwise, handle);
}
NewReduce(Comparison_reduce) {
	YNode* node;
	ExtractCoords(file, line, charPos, handle);
	ExpectReduce(&node, bitwise, L"Expected expression", ;, handle);
	if (AssertOperator(handle->tokens[0], AssignOperator)&&
	AssertOperator(handle->tokens[1], AssignOperator)) {
		shift(handle);
		shift(handle);
		YNode* left;
		ExpectReduce(&left, bitwise, L"Expected expression", node->free(node),
				handle);
		node = NEW_BINARY(BEquals, node, left);
	} else if (AssertOperator(handle->tokens[0], LogicalNotOperator)&&
	AssertOperator(handle->tokens[1], AssignOperator)) {
		shift(handle);
		shift(handle);
		YNode* left;
		ExpectReduce(&left, bitwise, L"Expected expression", node->free(node),
				handle);
		node = NEW_BINARY(NotEquals, node, left);
	} else if (AssertOperator(handle->tokens[0], GreaterOperator)&&
	AssertOperator(handle->tokens[1], AssignOperator)) {
		shift(handle);
		shift(handle);
		YNode* left;
		ExpectReduce(&left, bitwise, L"Expected expression", node->free(node),
				handle);
		node = NEW_BINARY(GreaterOrEquals, node, left);
	} else if (AssertOperator(handle->tokens[0], LesserOperator)&&
	AssertOperator(handle->tokens[1], AssignOperator)) {
		shift(handle);
		shift(handle);
		YNode* left;
		ExpectReduce(&left, bitwise, L"Expected expression", node->free(node),
				handle);
		node = NEW_BINARY(LesserOrEquals, node, left);
	} else if (AssertOperator(handle->tokens[0], LesserOperator)) {
		shift(handle);
		YNode* left;
		ExpectReduce(&left, bitwise, L"Expected expression", node->free(node),
				handle);
		node = NEW_BINARY(Lesser, node, left);
	} else if (AssertOperator(handle->tokens[0], GreaterOperator)) {
		shift(handle);
		YNode* left;
		ExpectReduce(&left, bitwise, L"Expected expression", node->free(node),
				handle);
		node = NEW_BINARY(Greater, node, left);
	}
	SetCoords(node, file, line, charPos);
	return node;
}

NewValidate(Logical_not_validate) {
	return Validate(comparison, handle)
			|| AssertOperator(handle->tokens[0], LogicalNotOperator);
}
NewReduce(Logical_not_reduce) {
	YNode* node;
	ExtractCoords(file, line, charPos, handle);
	if (AssertOperator(handle->tokens[0], LogicalNotOperator)) {
		shift(handle);
		ExpectReduce(&node, comparison, L"Expected expression", ;, handle);
		node = NEW_UNARY(LogicalNot, node);
	} else {
		ExpectReduce(&node, comparison, L"Expected expression", ;, handle);
	}
	SetCoords(node, file, line, charPos);
	return node;
}

NewValidate(Logical_ops_validate) {
	return Validate(logical_not, handle);
}
NewReduce(Logical_ops_reduce) {
	YNode* node;
	ExtractCoords(file, line, charPos, handle);
	ExpectReduce(&node, logical_not, L"Expected expression", ;, handle);
	while (((AssertOperator(handle->tokens[0], AndOperator)
			&& AssertOperator(handle->tokens[1], AndOperator))
			|| (AssertOperator(handle->tokens[0], OrOperator)
					&& AssertOperator(handle->tokens[1], OrOperator)))
			&& !AssertOperator(handle->tokens[2], AssignOperator)) {
		YBinaryOperation op;
		if (AssertOperator(handle->tokens[0], AndOperator))
			op = LogicalAnd;
		else
			op = LogicalOr;
		shift(handle);
		shift(handle);
		YNode* left;
		ExpectReduce(&left, logical_not, L"Expected expression",
				node->free(node)
				;, handle);
		node = NEW_BINARY(op, node, left);
	}
	SetCoords(node, file, line, charPos);
	return node;
}

NewValidate(Expr_validate) {
	return AssertKeyword(handle->tokens[0], IfKeyword)
			|| AssertKeyword(handle->tokens[0], TryKeyword)
			|| AssertKeyword(handle->tokens[0], SwitchKeyword)
			|| AssertKeyword(handle->tokens[0], UsingKeyword)
			|| AssertKeyword(handle->tokens[0], WithKeyword)
			|| AssertKeyword(handle->tokens[0], BreakKeyword)
			|| AssertKeyword(handle->tokens[0], ContinueKeyword)
			|| AssertKeyword(handle->tokens[0], PassKeyword)
			|| AssertKeyword(handle->tokens[0], WhileKeyword)
			|| AssertKeyword(handle->tokens[0], DoKeyword)
			|| AssertKeyword(handle->tokens[0], ForKeyword)
			|| AssertKeyword(handle->tokens[0], ForeachKeyword)
			|| AssertKeyword(handle->tokens[0], ReturnKeyword)
			|| AssertKeyword(handle->tokens[0], ThrowKeyword)
			|| (AssertToken(handle->tokens[0], TokenIdentifier)
					&& AssertOperator(handle->tokens[1], ColonOperator)
					&& (AssertKeyword(handle->tokens[2], WhileKeyword)
							|| AssertKeyword(handle->tokens[2], ForeachKeyword)
							|| AssertKeyword(handle->tokens[2], DoKeyword)
							|| AssertKeyword(handle->tokens[2], ForKeyword)))
			|| handle->grammar.logical_ops.validate(handle);
}
NewReduce(Expr_reduce) {

	YNode* out;
	ExtractCoords(file, line, charPos, handle);
	if (AssertKeyword(handle->tokens[0], IfKeyword)) {
		/*Parses 'if' statement*/
		shift(handle);
		YNode* cond;
		YNode* body;
		bool parentheses = false;
		if (AssertOperator(handle->tokens[0], OpeningParentheseOperator)) {
			shift(handle);
			parentheses = true;
		}
		ExpectReduce(&cond, expression, L"Expected expression", ;, handle);
		if (parentheses) {
			ExpectOperator(handle->tokens[0], ClosingParentheseOperator,
				L"Expected ')'", cond->free(cond), handle);
			shift(handle);
		}
		ExpectReduce(&body, statement, L"Expected statement", cond->free(cond),
				handle);
		YNode* elseBody = NULL;
		if (AssertKeyword(handle->tokens[0], ElseKeyword)) {
			/*Parses 'else' statement if available*/
			shift(handle);
			ExpectReduce(&elseBody, statement, L"Expected statement", {
				cond->free(cond)
				;
				body->free(body)
				;
			}, handle);
		}
		out = newConditionNode(cond, body, elseBody);
	} else if (AssertKeyword(handle->tokens[0], TryKeyword)) {
		shift(handle);
		YNode* tryBody;
		/*Parses 'try' body*/
		ExpectReduce(&tryBody, statement, L"Expected statement", ;, handle);
		YNode* catchRef = NULL;
		YNode* catchBody = NULL;
		YNode* elseBody = NULL;
		YNode* finBody = NULL;
		if (AssertKeyword(handle->tokens[0], CatchKeyword)) {
			/*Parses 'catch' argument and body*/
			shift(handle);
			bool parentheses = false;
			if (AssertOperator(handle->tokens[0], OpeningParentheseOperator)) {
				shift(handle);
				parentheses = true;
			}
			ExpectReduce(&catchRef, expression, L"Expected expression",
					tryBody->free(tryBody), handle);
			if (parentheses) {
				ExpectOperator(handle->tokens[0], ClosingParentheseOperator,
					L"Expected ')'", tryBody->free(tryBody), handle);
				shift(handle);
			}
			ExpectReduce(&catchBody, statement, L"Expected statement", {
				tryBody->free(tryBody)
				;
				catchRef->free(catchRef)
				;
			}, handle);
		}
		if (AssertKeyword(handle->tokens[0], ElseKeyword)) {
			/*Parses 'else' body*/
			shift(handle);
			ExpectReduce(&elseBody, statement, L"Expected statement",
					{tryBody->free(tryBody); if (catchRef!=NULL) { catchRef->free(catchRef); catchBody->free(catchBody); } },
					handle);
		}
		if (AssertKeyword(handle->tokens[0], FinallyKeyword)) {
			/*Parses 'finally' body*/
			shift(handle);
			ExpectReduce(&finBody, statement, L"Expected statement",
					{tryBody->free(tryBody); if (catchRef!=NULL) { catchRef->free(catchRef); catchBody->free(catchBody); } if (elseBody!=NULL) elseBody->free(elseBody); },
					handle);
		}
		out = newTryNode(tryBody, catchRef, catchBody, elseBody, finBody);
	} else if (AssertKeyword(handle->tokens[0], SwitchKeyword)) {
		YNode* value = NULL;
		YNode* defCase = NULL;
		YCaseNode* cases = NULL;
		size_t case_count = 0;

#define freestmt {if (value!=NULL) value->free(value);\
					if (defCase!=NULL) defCase->free(defCase);\
					for (size_t i=0;i<case_count;i++) {\
						cases[i].value->free(cases[i].value);\
						cases[i].stmt->free(cases[i].stmt);\
					}\
					free(cases);}

		shift(handle);

		bool parentheses = false;
		if (AssertOperator(handle->tokens[0], OpeningParentheseOperator)) {
			shift(handle);
			parentheses = true;
		}
		ExpectReduce(&value, expression, L"Expected expression", freestmt,
				handle);
		if (parentheses) {
			ExpectOperator(handle->tokens[0], ClosingParentheseOperator,
				L"Expected ')'", value->free(value), handle);
			shift(handle);
		}
		ExpectOperator(handle->tokens[0], OpeningBraceOperator, L"Expected '{",
				freestmt, handle);
		shift(handle);
		while (!AssertOperator(handle->tokens[0], ClosingBraceOperator)) {
			if (AssertKeyword(handle->tokens[0], CaseKeyword)) {
				shift(handle);
				YNode* cval = NULL;
				YNode* cstmt = NULL;
				ExpectReduce(&cval, expression, L"Expected expression",
						freestmt, handle);
				ExpectReduce(&cstmt, statement, L"Expected statement",
						{freestmt; cval->free(cval);}, handle);
				cases = realloc(cases, sizeof(YCaseNode) * (++case_count));
				cases[case_count - 1].value = cval;
				cases[case_count - 1].stmt = cstmt;
			} else if (AssertKeyword(handle->tokens[0], DefaultKeyword)) {
				if (defCase != NULL)
					ParseError(L"Default case already defined", freestmt,
							handle);
				shift(handle);
				ExpectReduce(&defCase, statement, L"Expected statement",
						freestmt, handle);
			} else
				ParseError(L"Expected 'case, 'default' or '}", freestmt, handle);
		}
		shift(handle);
#undef freestmt
		out = newSwitchNode(value, cases, case_count, defCase);
	} else if (AssertKeyword(handle->tokens[0], UsingKeyword)) {
		shift(handle);
		size_t length = 1;
		YNode** scopes = malloc(sizeof(YNode*));
		bool parentheses = false;
		if (AssertOperator(handle->tokens[0], OpeningParentheseOperator)) {
			shift(handle);
			parentheses = true;
		}
		ExpectReduce(&scopes[0], expr, L"Expected expresion", free(scopes),
				handle);
#define freestmt {\
            for (size_t i=0;i<length;i++) {\
                scopes[i]->free(scopes[i]);\
            }\
            free(scopes);\
        }
		while (AssertOperator(handle->tokens[0], CommaOperator)) {
			shift(handle);
			YNode* n;
			ExpectReduce(&n, expr, L"Expect expression", freestmt, handle);
			length++;
			scopes = realloc(scopes, sizeof(YNode*) * length);
			scopes[length - 1] = n;
		}
		if (parentheses) {
			ExpectOperator(handle->tokens[0], ClosingParentheseOperator,
				L"Expected ')'", freestmt, handle);
			shift(handle);
		}
		YNode* body;
		ExpectReduce(&body, statement, L"Expected statement", freestmt, handle);
#undef freestmt
		out = newUsingNode(scopes, length, body);
	} else if (AssertKeyword(handle->tokens[0], WithKeyword)) {
		shift(handle);
		YNode* scope;
		YNode* body;
		bool parentheses = false;
		if (AssertOperator(handle->tokens[0], OpeningParentheseOperator)) {
			shift(handle);
			parentheses = true;
		}
		ExpectReduce(&scope, expression, L"Expected expression", ;, handle);
		if (parentheses) {
			ExpectOperator(handle->tokens[0], ClosingParentheseOperator,
				L"Expected ')'", scope->free(scope), handle);
			shift(handle);
		}
		ExpectReduce(&body, statement, L"Expected statement",
				scope->free(scope), handle);
		out = newWithNode(scope, body);
	} else if (AssertKeyword(handle->tokens[0], PassKeyword)) {
		shift(handle);
		out = newPassNode();
	} else if (AssertKeyword(handle->tokens[0], BreakKeyword)) {
		shift(handle);
		wchar_t* id = NULL;
		if (AssertToken(handle->tokens[0], TokenIdentifier)) {
			id = handle->tokens[0].value.id;
			shift(handle);
		}
		out = newBreakNode(id);
	} else if (AssertKeyword(handle->tokens[0], ContinueKeyword)) {
		shift(handle);
		wchar_t* id = NULL;
		if (AssertToken(handle->tokens[0], TokenIdentifier)) {
			id = handle->tokens[0].value.id;
			shift(handle);
		}
		out = newContinueNode(id);
	} else if (AssertKeyword(handle->tokens[0], ReturnKeyword)) {
		shift(handle);
		YNode* value;
		if (Validate(expression, handle)) {
			ExpectReduce(&value, expression, L"Expected expression", ;, handle);
		} else
			value = newNullNode();
		out = newReturnNode(value);
	} else if (AssertKeyword(handle->tokens[0], ThrowKeyword)) {
		shift(handle);
		YNode* value;
		ExpectReduce(&value, expression, L"Expected expression", ;, handle);
		out = newThrowNode(value);
	} else if (AssertKeyword(handle->tokens[0], WhileKeyword)
			|| (AssertToken(handle->tokens[0], TokenIdentifier)
					&& AssertOperator(handle->tokens[1], ColonOperator)
					&& (AssertKeyword(handle->tokens[2], WhileKeyword)))) {
		wchar_t* id = NULL;
		if (AssertToken(handle->tokens[0], TokenIdentifier)) {
			id = handle->tokens[0].value.id;
			shift(handle);
			shift(handle);
		}
		shift(handle);
		YNode* cond;
		YNode* body;
		bool parentheses = false;
		if (AssertOperator(handle->tokens[0], OpeningParentheseOperator)) {
			shift(handle);
			parentheses = true;
		}
		ExpectReduce(&cond, expression, L"Expected expression", ;, handle);
		if (parentheses) {
			ExpectOperator(handle->tokens[0], ClosingParentheseOperator,
				L"Expected ')'", cond->free(cond), handle);
			shift(handle);
		}
		ExpectReduce(&body, statement, L"Expected statement", cond->free(cond),
				handle);
		return newWhileLoopNode(id, true, cond, body);
	} else if (AssertKeyword(handle->tokens[0], DoKeyword)
			|| (AssertToken(handle->tokens[0], TokenIdentifier)
					&& AssertOperator(handle->tokens[1], ColonOperator)
					&& (AssertKeyword(handle->tokens[2], DoKeyword)))) {
		wchar_t* id = NULL;
		if (AssertToken(handle->tokens[0], TokenIdentifier)) {
			id = handle->tokens[0].value.id;
			shift(handle);
			shift(handle);
		}
		shift(handle);
		YNode* body;
		ExpectReduce(&body, statement, L"Expected statement", ;, handle);
		if (AssertKeyword(handle->tokens[0], WhileKeyword)) {
			shift(handle);
			YNode* cond;
			bool parentheses = false;
			if (AssertOperator(handle->tokens[0], OpeningParentheseOperator)) {
				shift(handle);
				parentheses = true;
			}
			ExpectReduce(&cond, expression, L"Expected expression",
					body->free(body), handle);
			if (parentheses) {
				ExpectOperator(handle->tokens[0], ClosingParentheseOperator,
					L"Expected ')'", body->free(body); cond->free(cond);, handle);
				shift(handle);
			}
			return newWhileLoopNode(id, false, cond, body);
		} else {
			return newLoopNode(id, body);
		}
	} else if (AssertKeyword(handle->tokens[0], ForKeyword)
			|| (AssertToken(handle->tokens[0], TokenIdentifier)
					&& AssertOperator(handle->tokens[1], ColonOperator)
					&& (AssertKeyword(handle->tokens[2], ForKeyword)))) {
		wchar_t* id = NULL;
		if (AssertToken(handle->tokens[0], TokenIdentifier)) {
			id = handle->tokens[0].value.id;
			shift(handle);
			shift(handle);
		}
		shift(handle);
		YNode* init;
		YNode* cond;
		YNode* loop;
		YNode* body;
		bool parentheses = false;
		if (AssertOperator(handle->tokens[0], OpeningParentheseOperator)) {
			shift(handle);
			parentheses = true;
		}
		ExpectReduce(&init, statement, L"Expects statement", ;, handle);
		ExpectReduce(&cond, statement, L"Expects statement", init->free(init),
				handle);
		ExpectReduce(&loop, statement, L"Expects statement", {
			init->free(init)
			;
			cond->free(cond)
			;
		}, handle);
		if (parentheses) {
			ExpectOperator(handle->tokens[0], ClosingParentheseOperator,
				L"Expected ')'", init->free(init);
													cond->free(cond);
													loop->free(loop);, handle);
			shift(handle);
		}
		ExpectReduce(&body, statement, L"Expects statement", {
			init->free(init)
			;
			cond->free(cond)
			;
			loop->free(loop)
			;
		}, handle);
		return newForLoopNode(id, init, cond, loop, body);
	} else if (AssertKeyword(handle->tokens[0], ForeachKeyword)
			|| (AssertToken(handle->tokens[0], TokenIdentifier)
					&& AssertOperator(handle->tokens[1], ColonOperator)
					&& (AssertKeyword(handle->tokens[2], ForeachKeyword)))) {
		wchar_t* id = NULL;
		if (AssertToken(handle->tokens[0], TokenIdentifier)) {
			id = handle->tokens[0].value.id;
			shift(handle);
			shift(handle);
		}
		shift(handle);
		YNode* refnode;
		YNode* col;
		YNode* body;

		bool parentheses = false;
		if (AssertOperator(handle->tokens[0], OpeningParentheseOperator)) {
			shift(handle);
			parentheses = true;
		}
		ExpectReduce(&refnode, expression, L"Expected expression", ;, handle);
		ExpectOperator(handle->tokens[0], ColonOperator, L"Expected ':'",
				refnode->free(refnode), handle);
		shift(handle);
		ExpectReduce(&col, expression, L"Expected expression",
				refnode->free(refnode), handle);
		if (parentheses) {
			ExpectOperator(handle->tokens[0], ClosingParentheseOperator,
				L"Expected ')'", refnode->free(refnode);
													col->free(col);, handle);
			shift(handle);
		}
		ExpectReduce(&body, expression, L"Expected statement", {
			refnode->free(refnode)
			;
			col->free(col)
			;
		}, handle);
		out = newForeachLoopNode(id, refnode, col, body);
	} else
		ExpectReduce(&out, logical_ops, L"Expected expression", ;, handle);
	SetCoords(out, file, line, charPos);
	return out;
}

NewValidate(Expression_validate) {
	return Validate(expr, handle)
			|| AssertKeyword(handle->tokens[0], VarKeyword)
			|| AssertKeyword(handle->tokens[0], DelKeyword);
}
NewReduce(Expression_reduce) {
	/*YNode* node;
	 ExpectReduce(&node, expr, L"Expected expression", ;, handle);
	 return node;*/
	ExtractCoords(file, line, charPos, handle);
	if (AssertKeyword(handle->tokens[0], DelKeyword)) {
		shift(handle);
		size_t length = 1;
		YNode** list = malloc(sizeof(YNode*) * length);
		ExpectReduce(&list[0], expr, L"Expected expression", free(list), handle);
#define freestmt {\
            for (size_t i=0;i<length;i++)\
                list[i]->free(list[i]);\
            free(list);\
		}
		while (AssertOperator(handle->tokens[0], CommaOperator)) {
			shift(handle);
			YNode* n;
			ExpectReduce(&n, expr, L"Expected expression", freestmt, handle);
			length++;
			list = realloc(list, sizeof(YNode*) * length);
			list[length - 1] = n;
		}
#undef freestmt
		YNode* out = newDeleteNode(list, length);
		SetCoords(out, file, line, charPos);
		return out;
	}

	bool newVar = false;
	if (AssertKeyword(handle->tokens[0], VarKeyword)) {
		shift(handle);
		newVar = true;
	}
	YNode* type = NULL;
	if (AssertOperator(handle->tokens[0], MinusOperator)&&
	AssertOperator(handle->tokens[1], GreaterOperator)) {
		shift(handle);
		shift(handle);
		ExpectReduce(&type, expr, L"Expected expression", ;, handle);
	}
	YNode* node = NULL;
	ExpectReduce(&node, expr, L"Expected expression",
			if (type!=NULL) type->free(type);, handle);
	YNode** dests = NULL;
	size_t dest_count = 0;
	if (AssertOperator(handle->tokens[0], CommaOperator)) {
		dests = malloc(sizeof(YNode*));
		dests[0] = node;
		dest_count++;
		while (AssertOperator(handle->tokens[0], CommaOperator)) {
			shift(handle);
			YNode* n;
			ExpectReduce(&n, expr, L"Expected expression", {
				for (size_t i = 0; i < dest_count; i++)
					dests[i]->free(dests[i])
					;
				free(dests)
				;
			}, handle);
			dests = realloc(dests, sizeof(YNode*) * (++dest_count));
			dests[dest_count - 1] = n;
		}
	}
	if (AssertOperator(handle->tokens[0], AssignOperator)
			|| ((AssertOperator(handle->tokens[0], PlusOperator)
					|| AssertOperator(handle->tokens[0], MinusOperator)
					|| AssertOperator(handle->tokens[0], MultiplyOperator)
					|| AssertOperator(handle->tokens[0], DivideOperator)
					|| AssertOperator(handle->tokens[0], ModuloOperator)
					|| AssertOperator(handle->tokens[0], AndOperator)
					|| AssertOperator(handle->tokens[0], OrOperator)
					|| AssertOperator(handle->tokens[0], XorOperator))
					&& AssertOperator(handle->tokens[1], AssignOperator))
			|| (((AssertOperator(handle->tokens[0], MultiplyOperator)
					&& AssertOperator(handle->tokens[1], MultiplyOperator))
					|| (AssertOperator(handle->tokens[0], LesserOperator)
							&& AssertOperator(handle->tokens[1], LesserOperator))
					|| (AssertOperator(handle->tokens[0], GreaterOperator)
							&& AssertOperator(handle->tokens[1],
									GreaterOperator))
					|| (AssertOperator(handle->tokens[0], AndOperator)
							&& AssertOperator(handle->tokens[1], AndOperator))
					|| (AssertOperator(handle->tokens[0], OrOperator)
							&& AssertOperator(handle->tokens[1], OrOperator)))
					&& AssertOperator(handle->tokens[2], AssignOperator))) {
		if (dests == NULL) {
			dests = malloc(sizeof(YNode*));
			dests[0] = node;
			dest_count++;
		}
		YAssignmentOperation op;
		if (AssertOperator(handle->tokens[0], PlusOperator)) {
			op = AAddAssign;
			shift(handle);
		} else if (AssertOperator(handle->tokens[0], MinusOperator)) {
			op = ASubAssign;
			shift(handle);
		} else if (AssertOperator(handle->tokens[0], MultiplyOperator)&&
		AssertOperator(handle->tokens[1], MultiplyOperator)) {
			op = APowerAssign;
			shift(handle);
			shift(handle);
		} else if (AssertOperator(handle->tokens[0], MultiplyOperator)) {
			op = AMulAssign;
			shift(handle);
		} else if (AssertOperator(handle->tokens[0], DivideOperator)) {
			op = ADivAssign;
			shift(handle);
		} else if (AssertOperator(handle->tokens[0], ModuloOperator)) {
			op = AModAssign;
			shift(handle);
		} else if (AssertOperator(handle->tokens[0], GreaterOperator)&&
		AssertOperator(handle->tokens[1], GreaterOperator)) {
			op = AShiftRightAssign;
			shift(handle);
			shift(handle);
		} else if (AssertOperator(handle->tokens[0], LesserOperator)&&
		AssertOperator(handle->tokens[1], LesserOperator)) {
			op = AShiftLeftAssign;
			shift(handle);
			shift(handle);
		} else if (AssertOperator(handle->tokens[0], AndOperator)&&
		AssertOperator(handle->tokens[1], AndOperator)) {
			op = ALogicalAndAssign;
			shift(handle);
			shift(handle);
		} else if (AssertOperator(handle->tokens[0], OrOperator)&&
		AssertOperator(handle->tokens[1], OrOperator)) {
			op = ALogicalOrAssign;
			shift(handle);
			shift(handle);
		} else if (AssertOperator(handle->tokens[0], AndOperator)) {
			op = AAndAssign;
			shift(handle);
		} else if (AssertOperator(handle->tokens[0], OrOperator)) {
			op = AOrAssign;
			shift(handle);
		} else if (AssertOperator(handle->tokens[0], XorOperator)) {
			op = AXorAssign;
			shift(handle);
		} else {
			op = AAssign;
		}
		if (op != AAssign)
			for (size_t i = 0; i < dest_count; i++) {
				if (dests[i]->type == FilledArrayN)
					ParseError(L"Can only assign to a tuple",
							{ for (size_t i=0; i<dest_count; i++) dests[i]->free(dests[i]); free(dests); if (type!=NULL) type->free(type); },
							handle);
			}
		shift(handle);

		size_t slength = 1;
		YNode** srcs = malloc(sizeof(YNode*) * slength);
		ExpectReduce(&srcs[0], expr, L"Expected expression",
				{ for (size_t i=0; i<dest_count; i++) dests[i]->free(dests[i]); free(dests); if (type!=NULL) type->free(type); free(srcs); },
				handle);
		while (AssertOperator(handle->tokens[0], CommaOperator)) {
			shift(handle);
			YNode* nd;
			ExpectReduce(&nd, expr, L"Expected expression",
					{ for (size_t i=0; i<dest_count; i++) dests[i]->free(dests[i]); free(dests); for (size_t i=0; i<slength; i++) srcs[i]->free(srcs[i]); free(srcs); if (type!=NULL) type->free(type); node->free(node); },
					handle);
			slength++;
			srcs = realloc(srcs, sizeof(YNode*) * slength);
			srcs[slength - 1] = nd;
		}
		YNode* out = newAssignmentNode(op, newVar, type, srcs, slength, dests,
				dest_count);
		SetCoords(out, file, line, charPos);
		return out;
	}
	if (newVar || type != NULL) {
		if (dests == NULL) {
			dests = malloc(sizeof(YNode*));
			dests[0] = node;
			dest_count++;
		}
		YNode** srcs = malloc(sizeof(YNode*));
		srcs[0] = newNullNode();
		YNode* out = newAssignmentNode(AAssign, newVar, type, srcs, 1, dests,
				dest_count);
		SetCoords(out, file, line, charPos);
		return out;
	}
	SetCoords(node, file, line, charPos);
	return node;
}

NewValidate(Statement_validate) {
	return Validate(expression, handle);
}
NewReduce(Statement_reduce) {
	YNode* node;
	ExpectReduce(&node, expression, L"Expected expression", ;, handle);
	if (AssertOperator(handle->tokens[0], SemicolonOperator))
		shift(handle);
	return node;
}

NewValidate(Function_validate) {
	return AssertKeyword(handle->tokens[0], FunctionKeyword)
			|| AssertKeyword(handle->tokens[0], MethodKeyword);
}
NewReduce(Function_reduce) {
	ExtractCoords(file, line, charPos, handle);
	bool meth = AssertKeyword(handle->tokens[0], MethodKeyword);
	shift(handle);
	ExpectToken(handle->tokens[0], TokenIdentifier, L"Expected identifier", ;,
			handle);
	wchar_t* id = handle->tokens[0].value.id;
	shift(handle);
	size_t length = 0;
	wchar_t** args = NULL;
	YNode** argTypes = NULL;
	bool vararg = false;
	ExpectOperator(handle->tokens[0], OpeningParentheseOperator,
			L"Expected '('", ;, handle);
	shift(handle);
	while (!AssertOperator(handle->tokens[0], ClosingParentheseOperator)) {
		if (AssertOperator(handle->tokens[0], QueryOperator)) {
			vararg = true;
			shift(handle);
		}
		ExpectToken(handle->tokens[0], TokenIdentifier, L"Expected identifier",
				{ free(args); for (size_t i=0;i<length;i++) if (argTypes[i]!=NULL) argTypes[i]->free(argTypes[i]); free(argTypes); },
				handle);
		length++;
		args = realloc(args, sizeof(wchar_t*) * length);
		args[length - 1] = handle->tokens[0].value.id;
		argTypes = realloc(argTypes, sizeof(YNode*) * length);
		argTypes[length - 1] = NULL;
		shift(handle);
		if (AssertOperator(handle->tokens[0], MinusOperator)&&
		AssertOperator(handle->tokens[1], GreaterOperator)) {
			shift(handle);
			shift(handle);
			ExpectReduce(&argTypes[length - 1], expr, L"Expected expression",
					{ free(args); for (size_t i=0;i<length;i++) if (argTypes[i]!=NULL) argTypes[i]->free(argTypes[i]); free(argTypes); },
					handle);
		}
		Expect(
				AssertOperator(handle->tokens[0], CommaOperator)||AssertOperator(handle->tokens[0], ClosingParentheseOperator),
				L"Expects ')' or ','",
				{ free(args); for (size_t i=0;i<length;i++) if (argTypes[i]!=NULL) argTypes[i]->free(argTypes[i]); free(argTypes); },
				handle);
		Expect(
				!(vararg&&!AssertOperator(handle->tokens[0], ClosingParentheseOperator)),
				L"Vararg must be last, argument",
				{ free(args); for (size_t i=0;i<length;i++) if (argTypes[i]!=NULL) argTypes[i]->free(argTypes[i]); free(argTypes); },
				handle);
		if (AssertOperator(handle->tokens[0], CommaOperator))
			shift(handle);
	}
	shift(handle);
	YNode* retType = NULL;
	if (AssertOperator(handle->tokens[0], MinusOperator)&&
	AssertOperator(handle->tokens[1], GreaterOperator)) {
		shift(handle);
		shift(handle);
		ExpectReduce(&retType, expr, L"Expected expression",
				{ free(args); for (size_t i=0;i<length;i++) if (argTypes[i]!=NULL) argTypes[i]->free(argTypes[i]); free(argTypes); },
				handle);
	}
	YNode* body;
	ExpectReduce(&body, statement, L"Expected statement",
			{ free(args); for (size_t i=0;i<length;i++) if (argTypes[i]!=NULL) argTypes[i]->free(argTypes[i]); free(argTypes); if (retType!=NULL) retType->free(retType); },
			handle);
	YNode* out = newFunctionNode(id,
			(YLambdaNode*) newLambdaNode(meth, args, argTypes, length, vararg,
					retType, body));
	SetCoords(out, file, line, charPos);
	return out;
}

NewValidate(Root_validate) {
	return true;
}
NewReduce(Root_reduce) {
	ExtractCoords(file, line, charPos, handle);
	YFunctionBlock* funcs = NULL;
	size_t funcs_c = 0;

	YNode** block = NULL;
	size_t length = 0;

	while (handle->tokens[0].type != TokenEOF) {
		if (handle->grammar.statement.validate(handle)) {
			YNode* nd;
			nd = handle->grammar.statement.reduce(handle);
			if (nd == NULL)
				continue;
			length++;
			block = realloc(block, sizeof(YNode*) * length);
			block[length - 1] = nd;
		} else if (handle->grammar.function.validate(handle)) {
			YFunctionNode* func =
					(YFunctionNode*) handle->grammar.function.reduce(handle);
			if (func == NULL)
				continue;
			for (size_t i = 0; i < funcs_c; i++)
				if (funcs[i].id == func->name) {
					funcs[i].count++;
					funcs[i].lambda = realloc(funcs[i].lambda,
							sizeof(YLambdaNode*) * funcs[i].count);
					funcs[i].lambda[funcs[i].count - 1] = func->lambda;
					free(func);
					func = NULL;
					break;
				}
			if (func != NULL) {
				funcs_c++;
				funcs = realloc(funcs, sizeof(YFunctionBlock) * funcs_c);
				funcs[funcs_c - 1].id = func->name;
				funcs[funcs_c - 1].count = 1;
				funcs[funcs_c - 1].lambda = malloc(sizeof(YLambdaNode*));
				funcs[funcs_c - 1].lambda[0] = func->lambda;
				free(func);
				func = NULL;
			}
		} else {
			shift(handle);
		}
	}
	YNode* out = newBlockNode(block, length, funcs, funcs_c);
	out->type = RootN;
	SetCoords(out, file, line, charPos);
	return out;
}

void initGrammar(Grammar* g) {
	NewRule(g, constant, Constant_validate, Constant_reduce);
	NewRule(g, identifier, Identifier_validate, Identifier_reduce);
	NewRule(g, lambda, Lambda_validate, Lambda_reduce);
	NewRule(g, object, Object_validate, Object_reduce);
	NewRule(g, array, Parser_Array_validate, Parser_Array_reduce);
	NewRule(g, overload, Overload_validate, Overload_reduce);
	NewRule(g, interface, Interface_validate, Interface_reduce);
	NewRule(g, factor, Factor_validate, Factor_reduce);
	NewRule(g, reference, Reference_validate, Reference_reduce);
	NewRule(g, unary, Unary_validate, Unary_reduce);
	NewRule(g, power, Power_validate, Power_reduce);
	NewRule(g, mul_div, Mul_div_validate, Mul_div_reduce);
	NewRule(g, add_sub, Add_sub_validate, Add_sub_reduce);
	NewRule(g, bitshift, Bitshift_validate, Bitshift_reduce);
	NewRule(g, bitwise, Bitwise_validate, Bitwise_reduce);
	NewRule(g, comparison, Comparison_validate, Comparison_reduce);
	NewRule(g, logical_not, Logical_not_validate, Logical_not_reduce);
	NewRule(g, logical_ops, Logical_ops_validate, Logical_ops_reduce);
	NewRule(g, expr, Expr_validate, Expr_reduce);
	NewRule(g, expression, Expression_validate, Expression_reduce);
	NewRule(g, statement, Statement_validate, Statement_reduce);
	NewRule(g, function, Function_validate, Function_reduce);
	NewRule(g, root, Root_validate, Root_reduce);
}

YNode* parse(ParseHandle* handle) {
	initGrammar(&handle->grammar);
	return handle->grammar.root.reduce(handle);
}

