/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class yoyo_runtime_ILBytecode */

#ifndef _Included_yoyo_runtime_ILBytecode
#define _Included_yoyo_runtime_ILBytecode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     yoyo_runtime_ILBytecode
 * Method:    newProcedure
 * Signature: ()Lyoyo/runtime/ILProcedure;
 */
JNIEXPORT jobject JNICALL Java_yoyo_runtime_ILBytecode_newProcedure(JNIEnv *,
		jobject);

/*
 * Class:     yoyo_runtime_ILBytecode
 * Method:    getProcedure
 * Signature: (I)Lyoyo/runtime/ILProcedure;
 */
JNIEXPORT jobject JNICALL Java_yoyo_runtime_ILBytecode_getProcedure(JNIEnv *,
		jobject, jint);

/*
 * Class:     yoyo_runtime_ILBytecode
 * Method:    getProcedures
 * Signature: ()[Lyoyo/runtime/ILProcedure;
 */
JNIEXPORT jobjectArray JNICALL Java_yoyo_runtime_ILBytecode_getProcedures(
		JNIEnv *, jobject);

/*
 * Class:     yoyo_runtime_ILBytecode
 * Method:    getSymbolId
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_yoyo_runtime_ILBytecode_getSymbolId(JNIEnv *,
		jobject, jstring);

/*
 * Class:     yoyo_runtime_ILBytecode
 * Method:    getSymbolById
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_yoyo_runtime_ILBytecode_getSymbolById(JNIEnv *,
		jobject, jint);

/*
 * Class:     yoyo_runtime_ILBytecode
 * Method:    getSymbolIds
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_yoyo_runtime_ILBytecode_getSymbolIds(JNIEnv *,
		jobject);

/*
 * Class:     yoyo_runtime_ILBytecode
 * Method:    addIntegerConstant
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_yoyo_runtime_ILBytecode_addIntegerConstant(JNIEnv *,
		jobject, jlong);

/*
 * Class:     yoyo_runtime_ILBytecode
 * Method:    addFloatConstant
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_yoyo_runtime_ILBytecode_addFloatConstant(JNIEnv *,
		jobject, jdouble);

/*
 * Class:     yoyo_runtime_ILBytecode
 * Method:    addBooleanConstant
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_yoyo_runtime_ILBytecode_addBooleanConstant(JNIEnv *,
		jobject, jboolean);

/*
 * Class:     yoyo_runtime_ILBytecode
 * Method:    addStringConstant
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_yoyo_runtime_ILBytecode_addStringConstant(JNIEnv *,
		jobject, jstring);

/*
 * Class:     yoyo_runtime_ILBytecode
 * Method:    addNullConstant
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_yoyo_runtime_ILBytecode_addNullConstant(JNIEnv *,
		jobject);

/*
 * Class:     yoyo_runtime_ILBytecode
 * Method:    getConstant
 * Signature: (I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_yoyo_runtime_ILBytecode_getConstant(JNIEnv *,
		jobject, jint);

/*
 * Class:     yoyo_runtime_ILBytecode
 * Method:    getConstantIds
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_yoyo_runtime_ILBytecode_getConstantIds(
		JNIEnv *, jobject);

/*
 * Class:     yoyo_runtime_ILBytecode
 * Method:    export
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_yoyo_runtime_ILBytecode_export
(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
