/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class yoyo_runtime_ILProcedure */

#ifndef _Included_yoyo_runtime_ILProcedure
#define _Included_yoyo_runtime_ILProcedure
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     yoyo_runtime_ILProcedure
 * Method:    getIdentifier
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_yoyo_runtime_ILProcedure_getIdentifier(JNIEnv *,
		jobject);

/*
 * Class:     yoyo_runtime_ILProcedure
 * Method:    setRegisterCount
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_yoyo_runtime_ILProcedure_setRegisterCount
(JNIEnv *, jobject, jint);

/*
 * Class:     yoyo_runtime_ILProcedure
 * Method:    getRegisterCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_yoyo_runtime_ILProcedure_getRegisterCount(JNIEnv *,
		jobject);

/*
 * Class:     yoyo_runtime_ILProcedure
 * Method:    getCode
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_yoyo_runtime_ILProcedure_getCode(JNIEnv *,
		jobject);

/*
 * Class:     yoyo_runtime_ILProcedure
 * Method:    getCodeLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_yoyo_runtime_ILProcedure_getCodeLength(JNIEnv *,
		jobject);

/*
 * Class:     yoyo_runtime_ILProcedure
 * Method:    appendCode
 * Signature: (BIII)V
 */
JNIEXPORT void JNICALL Java_yoyo_runtime_ILProcedure_appendCode__BIII
(JNIEnv *, jobject, jbyte, jint, jint, jint);

/*
 * Class:     yoyo_runtime_ILProcedure
 * Method:    appendCode
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_yoyo_runtime_ILProcedure_appendCode___3B
(JNIEnv *, jobject, jbyteArray);

/*
 * Class:     yoyo_runtime_ILProcedure
 * Method:    addCodeTableEntry
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_yoyo_runtime_ILProcedure_addCodeTableEntry
(JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     yoyo_runtime_ILProcedure
 * Method:    addLabel
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_yoyo_runtime_ILProcedure_addLabel
(JNIEnv *, jobject, jint, jint);

/*
 * Class:     yoyo_runtime_ILProcedure
 * Method:    getLabel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_yoyo_runtime_ILProcedure_getLabel(JNIEnv *, jobject,
		jint);

/*
 * Class:     yoyo_runtime_ILProcedure
 * Method:    getLabels
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_yoyo_runtime_ILProcedure_getLabels(JNIEnv *,
		jobject);

/*
 * Class:     yoyo_runtime_ILProcedure
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_yoyo_runtime_ILProcedure_free
(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
