/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class yoyo_yji_YBindings */

#ifndef _Included_yoyo_yji_YBindings
#define _Included_yoyo_yji_YBindings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     yoyo_yji_YBindings
 * Method:    _get
 * Signature: (I)Lyoyo/yji/YJIValue;
 */
JNIEXPORT jobject JNICALL Java_yoyo_yji_YBindings__1get(JNIEnv *, jobject,
		jint);

/*
 * Class:     yoyo_yji_YBindings
 * Method:    _put
 * Signature: (IZLyoyo/yji/YJIValue;)V
 */
JNIEXPORT void JNICALL Java_yoyo_yji_YBindings__1put
(JNIEnv *, jobject, jint, jboolean, jobject);

/*
 * Class:     yoyo_yji_YBindings
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_yoyo_yji_YBindings_init
(JNIEnv *, jobject);

/*
 * Class:     yoyo_yji_YBindings
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_yoyo_yji_YBindings_destroy
(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
