/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class yoyo_runtime_YRuntime */

#ifndef _Included_yoyo_runtime_YRuntime
#define _Included_yoyo_runtime_YRuntime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     yoyo_runtime_YRuntime
 * Method:    _interpret
 * Signature: (I)Lyoyo/yji/YJIValue;
 */
JNIEXPORT jobject JNICALL Java_yoyo_runtime_YRuntime__1interpret(JNIEnv *,
		jobject, jint);

/*
 * Class:     yoyo_runtime_YRuntime
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_yoyo_runtime_YRuntime_init
(JNIEnv *, jobject);

/*
 * Class:     yoyo_runtime_YRuntime
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_yoyo_runtime_YRuntime_destroy
(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
