/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class yoyo_yji_YRunnable */

#ifndef _Included_yoyo_yji_YRunnable
#define _Included_yoyo_yji_YRunnable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     yoyo_yji_YRunnable
 * Method:    _invoke
 * Signature: ([Lyoyo/yji/YJIValue;)Lyoyo/yji/YJIValue;
 */
JNIEXPORT jobject JNICALL Java_yoyo_yji_YRunnable__1invoke(JNIEnv *, jobject,
		jobjectArray);

/*
 * Class:     yoyo_yji_YRunnable
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_yoyo_yji_YRunnable_init
(JNIEnv *, jobject);

/*
 * Class:     yoyo_yji_YRunnable
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_yoyo_yji_YRunnable_destroy
(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
